### ISSUE TITLE
AddressParser initialisation error

### ISSUE THREAD

**Issue by JananiPN19** [selva221724/pypostalwin#10]
I'm facing the following issue while trying to initialise AddressParser.

```
>>> parser = pypostalwin.AddressParser()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: AddressParser.__init__() missing 2 required positional arguments: 'address_parser_path' and 'libpostal_path'
```

Can you please tell me where am I going wrong here? 

I'm using the latest version. i.e. 0.0.4.

**Comment by JananiPN19** [comment]
Sorry didn't follow the first step I guess. :(

**Comment by selva221724** [comment]
i think there is an issue in the recent release ,can you please use this below , 


Please uninstall and reinstall the last version 


```
pip uninstall pypostalwin
pip install pypostalwin==0.0.3
```

**Comment by JananiPN19** [comment]
Hi, 

Thanks for the comment. 

However, while downloading and unpacking the libpostal.7z, it says "No files to process". Is there any updated file of libpostal that I can check? 
Your help will be appreciated :)
