### ISSUE TITLE
Address expansion Feature

### ISSUE THREAD

**Issue by philipslesmana** [selva221724/pypostalwin#4]
Hi Selva, sorry for beginner question..do we have address expansion feature in pypostalwin ? thanks :)

**Comment by selva221724** [comment]
Hi @philipslesmana , I appreciate your question. We are adding that in the next version. We will keep you posted here. THANKS!!! Soon you can expect that to be released. Also, we are making it easier, so that mysy2 is not needed to be installed

**Comment by selva221724** [comment]
Hi @philipslesmana , I have released new version with the address expansion feature `pypostalwin v0.0.3`

<img alt="image" src="https://giffiles.alphacoders.com/208/208633.gif">

Please uninstall and reinstall the updated package and enjoy the address expansion feature !! 

```
pip uninstall pypostalwin
pip install pypostalwin==0.0.3
```

if it is a new 'env', you can use 'pip' without mentioning the version,

```
pip install pypostalwin
```

Thanks for your ASK !!
